CREATE TABLE produtos (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(150) NOT NULL,
    descricao TEXT,
    preco NUMERIC(10,2) NOT NULL CHECK (preco > 0),
    quantidade_estoque INT NOT NULL CHECK (quantidade_estoque >= 0)
);
CREATE TABLE clientes (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(150) NOT NULL,
    email VARCHAR(150),
    telefone VARCHAR(30)
);
CREATE TABLE vendas (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    data_venda TIMESTAMP NOT NULL DEFAULT NOW(),
    cliente_id INT NOT NULL,
    valor_total NUMERIC(12,2) NOT NULL DEFAULT 0,

    CONSTRAINT fk_vendas_clientes FOREIGN KEY (cliente_id) REFERENCES clientes(id)
        ON DELETE RESTRICT
);
CREATE TABLE venda_itens (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    venda_id INT NOT NULL,
    produto_id INT NOT NULL,
    quantidade INT NOT NULL CHECK (quantidade > 0),
    preco_venda NUMERIC(10,2) NOT NULL CHECK (preco_venda > 0),

    CONSTRAINT fk_venda_itens_vendas  FOREIGN KEY (venda_id) REFERENCES vendas(id) ON DELETE cascade,

    CONSTRAINT fk_venda_itens_produtos 
        FOREIGN KEY (produto_id) 
        REFERENCES produtos(id)
        ON DELETE RESTRICT
);

);